### ISSUE TITLE
Question about the training in terms of the Epochs

### ISSUE THREAD

**Issue by Amazingren** [PangzeCheung/Dual-task-Pose-Transformer-Network#2]
Hey @PangzeCheung ,

Again me, hope everything goes well with you. 
1) I noticed the `niter` and `niter_decay` are all set to `100`. That's to say we need to train the entire model totally 200 epochs for each dataset?
2) Since I also find that the pre-trained checkpoints you provided for DeepFashion is at 190 epoch, while for market-1501, it is just iter 811200. So I am a bit confused on how should I choose a checkpoint between checkpoint stored by epoch or stored by total iters?
3) I alreadt succefully trained the Dual-Task PTN with 1 Nvidia TITAN xp gpu on Market-1501 dataset, it cost me around 4 days by now (Stil at Epoch 131). But there all lots of checkpoints named in two different ways as follows. I also want to ask is this all right?
![image](https://user-images.githubusercontent.com/31409716/158068269-a2bbb834-e4ff-4f79-8b6c-a5ea5a50772f.png)

Looking forward to you reply but not in a hurry~

Best Regards,

**Comment by PangzeCheung** [comment]
@Amazingren Thanks for your question. The results shown in our paper are tested on DeepFashion and Market1501 models trained with 190 epochs and 811200 steps, respectively.

For Deepfashion, DPTN does take around 200 epochs to train (over one week on NVIDIA A100 40GB PCIe). Results may converge after 170 epochs (see Figure 6 in our paper).  For market1501, your checkpoint outputs are correct. Due to the low resolution and fuzzy texture of Market1501, DPTN is prone to overfitting, and the test results may fluctuate between adjacent steps. You can test the model output in both formats to find the best model.

**Comment by Amazingren** [comment]
> @Amazingren Thanks for your question. The results shown in our paper are tested on DeepFashion and Market1501 models trained with 190 epochs and 811200 steps, respectively.
> 
> For Deepfashion, DPTN does take around 200 epochs to train (over one week on NVIDIA A100 40GB PCIe). Results may converge after 170 epochs (see Figure 6 in our paper). For market1501, your checkpoint outputs are correct. Due to the low resolution and fuzzy texture of Market1501, DPTN is prone to overfitting, and the test results may fluctuate between adjacent steps. You can test the model output in both formats to find the best model.

Got it! Thanks A lot!  :)
